### ISSUE TITLE
Why add Plugin '.../.../' to install with Vundle

### ISSUE THREAD

**Issue by momoneko** [IN3D/vim-raml#5]
The README says to add these 3 lines to install with Vundle
```
Plugin '.../.../'
Plugin 'IN3D/vim-raml'
Plugin '.../.../'
```
Is there any reason for the `Plugin '.../.../'` surrounding the package?

**Comment by IN3D** [comment]
Hi there, thanks for the issue!

No, I meant that only as an example that it could be loaded anywhere alongside the rest of your plugins. When I wrote it I was aware of a few Vim plugins that needed to be loaded as either the first or last plugin. In retrospect, this probably ends up being more confusing than intended. Especially the trailing slashes.

You only need to add `Plugin 'IN3D/vim-raml'` for this to work. Hope that clears it up. 👍

**Comment by momoneko** [comment]
Thanks for clearing that up.

You should probably remove those from the README. It is quite confusing.
